// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/gendata.proto

package gendata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Gendata service

func NewGendataEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "Gendata.Generate",
			Path:    []string{"/generate"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for Gendata service

type GendataService interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error)
}

type gendataService struct {
	c    client.Client
	name string
}

func NewGendataService(name string, c client.Client) GendataService {
	return &gendataService{
		c:    c,
		name: name,
	}
}

func (c *gendataService) Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error) {
	req := c.c.NewRequest(c.name, "Gendata.Generate", in)
	out := new(GenerateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gendata service

type GendataHandler interface {
	Generate(context.Context, *GenerateRequest, *GenerateResponse) error
}

func RegisterGendataHandler(s server.Server, hdlr GendataHandler, opts ...server.HandlerOption) error {
	type gendata interface {
		Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error
	}
	type Gendata struct {
		gendata
	}
	h := &gendataHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Gendata.Generate",
		Path:    []string{"/generate"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&Gendata{h}, opts...))
}

type gendataHandler struct {
	GendataHandler
}

func (h *gendataHandler) Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error {
	return h.GendataHandler.Generate(ctx, in, out)
}
